services:
  backend:
    build:
      context: ./src/backend
    volumes:
      - ./src/backend/pb_data:/pb_data
    ports:
      - "8090:8090"
    container_name: mmgcs_backend
    deploy:
      resources:
        limits:
          memory: 700m
    restart: always

  frontend:
    build:
      context: ./src/frontend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    ports:
      - "5173:5173"
    container_name: mmgcs_frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 700m
    restart: always

  webrtc:
    build: ./src/webrtc
    container_name: mmgcs_webrtc
    network_mode: host
    privileged: true
    restart: always
