services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    container_name: canarygc_frontend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          memory: 700m
    restart: always

  # Ardupilot SITL
  sitl:
    image: radarku/ardupilot-sitl:latest
    environment:
      - INSTANCE=0
      - LAT=33.79105092934356
      - LON=-84.37130870603511
      - ALT=0
      - DIR=0
      - MODEL=quad
      - SPEEDUP=1
      - VEHICLE=ArduCopter
    tty: true
    container_name: canarygc_sitl
    ports:
      - "5760:5760"
    healthcheck:
      timeout: 10s

  # PX4 SITL
  # sitl:
  #   build:
  #     context: ./src/sitl
  #     dockerfile: Dockerfile.px4
  #   container_name: canarygc_sitl
  #   ports:
  #     - "5760:5760"
  #   environment:
  #     - PX4_HOME_LAT=33.79105092934356
  #     - PX4_HOME_LON=-84.37130870603511
  #     - PX4_HOME_ALT=0
  #     - PX4_SIM_SPEED_FACTOR=1
  #     - PX4_VEHICLE=quad
  #   healthcheck:
  #     timeout: 10s