services:
  backend:
    build:
      context: ./src/backend
    volumes:
      - ./src/backend/pb_data:/pb_data
    ports:
      - "8090:8090"
    container_name: mmgcs_backend
    deploy:
      resources:
        limits:
          memory: 700m

  frontend:
    build:
      context: ./src/frontend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    container_name: mmgcs_frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - sitl

  # ArduPilot SITL Service - Uncomment for development
  # https://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html
  sitl:
    image: radarku/ardupilot-sitl:latest
    tty: true
    container_name: mmgcs_sitl
    environment:
      - INSTANCE=0
      - LAT=33.7909
      - LON=-84.3722
      - ALT=14
      - DIR=270
      - MODEL=+
      - SPEEDUP=1
      - VEHICLE=ArduCopter
    ports:
      - "5760:5760"