name: CI/CD Pipeline

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history, including tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Get the version
        id: get_version
        run: |
          VERSION=$(git tag | sort --version-sort | tail -n1)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}"

      - name: Build and push services
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo "Building version: $VERSION"

          # Build frontend service using the production compose file
          docker compose -f docker-compose.prod.yml build --platform linux/amd64,linux/arm64 frontend

          # Tag and push the service to Docker Hub
          docker tag mmgcs-frontend ${{ secrets.DOCKERHUB_USERNAME }}/mmgcs:$VERSION
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmgcs:$VERSION
          docker tag mmgcs-frontend ${{ secrets.DOCKERHUB_USERNAME }}/mmgcs:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmgcs:latest

          # Tag and push the service to GitHub Container Registry
          docker tag mmgcs-frontend ghcr.io/${{ github.repository_owner }}/mmgcs:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/mmgcs:$VERSION
          docker tag mmgcs-frontend ghcr.io/${{ github.repository_owner }}/mmgcs:latest
          docker push ghcr.io/${{ github.repository_owner }}/mmgcs:latest