name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push services
        run: |
          # Build frontend service using the production compose file
          docker compose -f docker-compose.prod.yml build frontend

          # Tag and push the service to Docker Hub
          docker tag frontend ${{ secrets.DOCKERHUB_USERNAME }}/mmgcs:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmgcs:latest

          # Tag and push the service to GitHub Container Registry
          docker tag frontend ghcr.io/${{ github.repository_owner }}/mmgcs:latest
          docker push ghcr.io/${{ github.repository_owner }}/mmgcs:latest
